title: IT thoughts...
author:
  name: joharr
  email: <myemailaddress>
description:
  Self-taught geekology...
baseurl: ""
url: <me>.github.io
twitter_username: <mine>
github_username:  <mine>

minima:
  skin: dark  # having no effect

theme: minima

plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-seo
  - jekyll-gzip
